#!/bin/bash

if [ "$EUID" != "0" ]; then
  echo "You must be root to run this script."
  exit 1
fi

SCRIPT_NAME="rftest4"
LXCDIR=/var/lib/lxc
MONGODB_CONF=/etc/mongodb.conf
MONGODB_PORT=27017
MONGODB_ADDR=192.168.10.1
CONTROLLER_PORT=6633
RF_HOME=..
export PATH=$PATH:/usr/local/bin:/usr/local/sbin
export PYTHONPATH=$PYTHONPATH:$RF_HOME

cd $RF_HOME

wait_port_listen() {
    port=$1
    while ! `nc -z localhost $port` ; do
        echo -n .
        sleep 1
    done
}

echo_bold() {
    echo -e "\033[1m${1}\033[0m"
}

kill_process_tree() {
    top=$1
    pid=$2

    children=`ps -o pid --no-headers --ppid ${pid}`

    for child in $children
    do
        kill_process_tree 0 $child
    done

    if [ $top -eq 0 ]; then
        kill -9 $pid &> /dev/null
    fi
}

reset() {
    init=$1;
    if [ $init -eq 1 ]; then
        echo_bold "-> Starting $SCRIPT_NAME";
    else
        echo_bold "-> Stopping child processes...";
        kill_process_tree 1 $$
    fi

    ovs-vsctl del-br dp0 &> /dev/null;
    ovs-vsctl emer-reset &> /dev/null;

    echo_bold "-> Stopping and resetting LXC VMs...";
    for vm in "rfvmV"
    do
        lxc-shutdown -n "$vm";
        while true
        do
            if lxc-info -q -n "$vm" | grep -q "STOPPED"; then
                break;
            fi
            echo -n .
            sleep 1
        done
    done

    echo_bold "-> Kill MongoDB instance 1, 2, 3..."     
    MONGOPID=`ps -ef | grep 'mongod' | grep -v grep | awk '{print $2}'`
    kill -15 $MONGOPID &> /dev/null

    echo_bold "-> Deleting (previous) run data...";
    rm -rf /home/routeflow/RouteFlow/rftest/mongo/data/*/*   
    rm -rf /var/lib/lxc/rfvmV/rootfs/opt/rfclient;
}
reset 1
trap "reset 0; exit 0" INT

echo_bold "-> Setting up the management bridge (lxcbr0)..."
ifconfig lxcbr0 $MONGODB_ADDR up

echo_bold "-> Setting up MongoDB instance 1..."
mongod -f /home/routeflow/RouteFlow/rftest/mongo/conf/master.conf --replSet rs0

echo_bold "-> Setting up MongoDB instance 2..."
mongod -f /home/routeflow/RouteFlow/rftest/mongo/conf/slave1.conf --replSet rs0

echo_bold "-> Setting up MongoDB instance 3..."
mongod -f /home/routeflow/RouteFlow/rftest/mongo/conf/slave2.conf --replSet rs0

echo_bold "-> Initializing Replica set..."

mongo --quiet 192.168.10.1:27017/db --eval "rs.initiate()"
# conferring if instance exists to master
while [[ `mongo --quiet 192.168.10.1:27017/db --eval "db.isMaster().ismaster"` == false ]]; do
    echo "Waiting instance becomes primary..."
    sleep 5       
done
# setting other instance 
mongo 192.168.10.1:27017/db --eval "load('/home/routeflow/RouteFlow/rftest/initReplicaSet.js')"

echo_bold "-> Waiting 20s for replica set intialization..."
sleep 20

echo_bold "-> Configuring the virtual machines..."
# Create the rfclient dir
mkdir /var/lib/lxc/rfvmV/rootfs/opt/rfclient

# Copy the rfclient executable
cp build/rfclient /var/lib/lxc/rfvmV/rootfs/opt/rfclient/rfclient

# We sleep for a few seconds to wait for the interfaces to go up
echo "#!/bin/sh" > /var/lib/lxc/rfvmV/rootfs/root/run_rfclient.sh
echo "sleep 3" >> /var/lib/lxc/rfvmV/rootfs/root/run_rfclient.sh
echo "/etc/init.d/quagga start" >> /var/lib/lxc/rfvmV/rootfs/root/run_rfclient.sh
echo "/opt/rfclient/rfclient > /var/log/rfclient.log" >> /var/lib/lxc/rfvmV/rootfs/root/run_rfclient.sh

chmod +x /var/lib/lxc/rfvmV/rootfs/root/run_rfclient.sh

echo_bold "-> Starting the controller and RFPRoxy..."
cd pox
./pox.py log.level --=INFO topology openflow.topology openflow.discovery rfproxy rfstats &
cd -
wait_port_listen $CONTROLLER_PORT

echo_bold "-> Starting RFServer..."
./rfserver/rfserver.py rftest/rftest4config.csv &

echo_bold "-> Starting the virtual machines..."
lxc-start -n rfvmV -d

echo_bold "-> Starting the control plane network (dp0 VS)..."
ovs-vsctl add-br dp0
for i in $(seq 9);
do
ovs-vsctl add-port dp0 rfvmV.$i;
done
ovs-vsctl set Bridge dp0 other-config:datapath-id=7266767372667673
ovs-vsctl set-controller dp0 tcp:127.0.0.1:$CONTROLLER_PORT

echo_bold "---"
echo_bold "This test is up and running."
echo_bold "Start Mininet:"
echo_bold "  $ sudo mn --custom mininet/custom/topo-8sw-8host.py --topo=rftest4"
echo_bold "    --controller=remote,ip=[host address],port=6633 --pre=ipconf4"
echo_bold "Replace [host address] with the address of this host's interface "
echo_bold "connected to the Mininet VM."
echo_bold "Then try pinging everything:"
echo_bold "  mininet> pingall"
echo_bold "You can stop this test by pressing CTRL+C."
echo_bold "---"
wait

exit 0
